name: Checkout Code

on:
  workflow_dispatch: {}
  push:
    branches:
      - daniel

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: shuttler-tw/shuttler-backend
          ref: daniel

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
      - run: |
          echo "Node version: $(node -v)"
          echo "Installing dependencies..."
          npm install -g pnpm
          pnpm install

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: |
          npm run lint | tee > $(date +%F)-eslint.log
          echo "eslint_msg<<EOF" >> ${GITHUB_OUTPUT}
          head -n 20 $(date +%F)-eslint.log >> ${GITHUB_OUTPUT}
          echo "..." >> ${GITHUB_OUTPUT}
          echo "EOF" >> ${GITHUB_OUTPUT}

      - name: Notify on Discord
        uses: appleboy/discord-action@v1.4.1
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: 'GITHUB_BOT'
          message: |
            **Commit Info**
            游녤 Triggered by: `${{ github.event_name }}`
            游릭 Repository: `${{ github.repository }}`
            游리 Branch: `${{ github.ref }}`
            游대 Commit: `${{ github.sha }}`
            **ESLint Report**
            ```
            ${{ steps.eslint.outputs.eslint_msg }}
            ```

      - name: Run Check Prettier Formatting
        id: prettier
        continue-on-error: true
        run: |
          npm run format:check | tee > $(date +%F)-prettier.log
          echo "prettier_msg<<EOF" >> ${GITHUB_OUTPUT}
          head -n 20 $(date +%F)-prettier.log >> ${GITHUB_OUTPUT}
          echo "..." >> ${GITHUB_OUTPUT}
          echo "EOF" >> ${GITHUB_OUTPUT}

      - name: Notify on Discord
        uses: appleboy/discord-action@v1.4.1
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: 'GITHUB_BOT'
          message: |
            **Commit Info**
            游녤 Triggered by: `${{ github.event_name }}`
            游릭 Repository: `${{ github.repository }}`
            游리 Branch: `${{ github.ref }}`
            游대 Commit: `${{ github.sha }}`
            **Prettier Report**
            ```
            ${{ steps.prettier.outputs.prettier_msg }}
            ```



